"""Smoke test — 3 script + MCP server 1줄 검증.

실행:
  .venv/bin/python3 tests/test_smoke.py
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SCRIPTS = ROOT / "scripts"
PY = sys.executable


def run(script, args):
    """script 실행 + stdout JSON 파싱."""
    cp = subprocess.run(
        [PY, str(SCRIPTS / script), *args],
        capture_output=True, text=True, check=True,
    )
    return json.loads(cp.stdout)


def test_get_logs():
    """get_logs.py — 최근 5건 + 필터링."""
    rows = run("get_logs.py", ["--limit", "5"])
    assert len(rows) == 5, f"expected 5 rows, got {len(rows)}"
    assert all("txn_id" in r for r in rows), "missing txn_id"
    # 시간 역순
    ts = [r["ts"] for r in rows]
    assert ts == sorted(ts, reverse=True), "not sorted desc"

    # 필터링
    pos_down = run("get_logs.py", ["--status", "POS_DOWN", "--limit", "3"])
    assert all(r["status"] == "POS_DOWN" for r in pos_down), "filter not applied"
    print("OK  get_logs       (5 rows + filter)")


def test_detect_anomaly():
    """detect_anomaly.py — 60분 윈도우 + by_store 분포."""
    result = run("detect_anomaly.py", ["--window", "60"])
    assert "total" in result and "anomalies" in result
    assert "by_store" in result and "top_issue" in result
    if result["total"] > 0 and result["anomalies"]:
        assert result["top_issue"] in result["anomalies"]
    print(f"OK  detect_anomaly  (total={result['total']}, top={result['top_issue']})")


def test_create_ticket():
    """create_ticket.py — JSONL append."""
    before = (ROOT / "data" / "tickets.jsonl").stat().st_size if (ROOT / "data" / "tickets.jsonl").exists() else 0
    t = run("create_ticket.py", [
        "--title", "smoke test ticket",
        "--body", "auto-generated by test_smoke.py",
        "--priority", "P4-Low",
        "--store", "SEL-001",
        "--category", "device",
    ])
    assert t["ticket_id"].startswith("OPS-")
    assert t["status"] == "open"
    after = (ROOT / "data" / "tickets.jsonl").stat().st_size
    assert after > before, "jsonl not appended"
    print(f"OK  create_ticket   ({t['ticket_id']})")


def test_mcp_server_loads():
    """mcp_server/server.py 가 import + 3 tool 등록 확인."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("srv", ROOT / "mcp_server" / "server.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    import asyncio
    tools = asyncio.run(mod.mcp.list_tools())
    names = {t.name for t in tools}
    assert names == {"get_logs", "detect_anomaly", "create_ticket"}, names
    print(f"OK  mcp_server      (3 tools: {sorted(names)})")


if __name__ == "__main__":
    print("Running smoke tests ...")
    print()
    test_get_logs()
    test_detect_anomaly()
    test_create_ticket()
    test_mcp_server_loads()
    print()
    print("✓ all 4 tests passed")
